# The groupName avoids naming conflicts on the Kubernetes API, it should be set by the
# author of the webhook a unique domain that the author owns. For
# example: bunnydns-webhook.libnare.net
# Once set to a unique domain name by the webhook author, it does not need to be further
# adjusted by the users of a webhook chart!
# The name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
groupName: bunnydns-webhook.libnare.net

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/libnare/cert-manager-webhook-bunnydns
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Webhook configuration
webhook:
  # The webhook will listen on this port
  port: 8443
  # Path for health checks
  healthPath: /healthz
