apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate-bundle, which is used to verify the
# webhook's TLS certificate.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:domain-solver
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:domain-solver
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
---
# Grant permission to read extension-apiserver-authentication configmap
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:auth-delegator
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
---
# Grant permission to read extension-apiserver-authentication configmap
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:auth-reader
  namespace: kube-system
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:domain-solver:cert-manager
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - "*"
    verbs:
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:domain-solver:cert-manager
  labels:
    {{- include "cert-manager-webhook-bunnydns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-bunnydns.fullname" . }}:domain-solver:cert-manager
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
